### ISSUE TITLE
Fatal Exception: java.lang.AssertionError No NameTypeIndex match for SHORT_DAYLIGHT

### ISSUE THREAD

**Issue by MichaelGao** [pubnative/pubnative-hybid-android-sdk#2]
Hi  we're facing the following issue on devices of Android 8.

sdk version: net.pubnative:hybid.sdk:2.12.1

Fatal Exception: java.lang.AssertionError
No NameTypeIndex match for SHORT_DAYLIGHT

android.icu.impl.TimeZoneNamesImpl$ZNames.getNameTypeIndex (TimeZoneNamesImpl.java:724)
android.icu.impl.TimeZoneNamesImpl$ZNames.getName (TimeZoneNamesImpl.java:790)
android.icu.impl.TimeZoneNamesImpl.getTimeZoneDisplayName (TimeZoneNamesImpl.java:183)
android.icu.text.TimeZoneNames.getDisplayName (TimeZoneNames.java:261)
java.util.TimeZone.getDisplayName (TimeZone.java:405)
java.util.Date.toString (Date.java:1066)
net.pubnative.lite.sdk.DiagnosticsManager.getDiagnosticsLog (DiagnosticsManager.java:94)
net.pubnative.lite.sdk.DiagnosticsManager.printDiagnosticsLog (DiagnosticsManager.java:76)
net.pubnative.lite.sdk.HyBid$1.onInfoLoaded (HyBid.java:136)
net.pubnative.lite.sdk.DeviceInfo$1.onHyBidAdvertisingIdFinish (DeviceInfo.java:125)
net.pubnative.lite.sdk.utils.HyBidAdvertisingId.onPostExecute (HyBidAdvertisingId.java:78)
net.pubnative.lite.sdk.utils.HyBidAdvertisingId.onPostExecute (HyBidAdvertisingId.java:34)

**Comment by eros902002** [comment]
Hi @MichaelGao. Thanks for the report. We'll look into it.

**Comment by eros902002** [comment]
@MichaelGao just checking with the version you reported. This is an older version and we solved this issue on version 2.13.0 if I'm not mistaken. I'd recommend that you use our latest one 2.15.0

**Comment by MichaelGao** [comment]
> @MichaelGao just checking with the version you reported. This is an older version and we solved this issue on version 2.13.0 if I'm not mistaken. I'd recommend that you use our latest one 2.15.0

Thanks a lot, we'll update to the latest sdk 2.15.

**Comment by eros902002** [comment]
Closing this one since it's been fixed.
