### ISSUE TITLE
android.database.sqlite.SQLiteException  table IMPRESSIION already exists (code 1 SQLITE_ERROR[1])

### ISSUE THREAD

**Issue by pendai** [pubnative/pubnative-hybid-android-sdk#4]
1 android.database.sqlite.SQLiteConnection.nativeExecuteForChangedRowCount(Native Method)
2 android.database.sqlite.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:1164)
3 android.database.sqlite.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:756)
4 android.database.sqlite.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:66)
5 android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:2438)
6 android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:2359)
7 net.pubnative.lite.sdk.db.DatabaseHelper.void onCreate(android.database.sqlite.SQLiteDatabase)(DatabaseHelper.java:41)
8 android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:482)
9 android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:387)
10 net.pubnative.lite.sdk.db.DBManager.net.pubnative.lite.sdk.db.DBManager open()(DBManager.java:32)
11 net.pubnative.lite.sdk.models.AdRequestFactory.void createAdRequest(java.lang.String,java.lang.String,net.pubnative.lite.sdk.models.AdSize,boolean,net.pubnative.lite.sdk.models.AdRequestFactory$Callback)(AdRequestFactory.java:107)
12 net.pubnative.lite.sdk.api.RequestManager.void requestAd()(RequestManager.java:201)
13 net.pubnative.lite.sdk.interstitial.HyBidInterstitialAd.void load()(HyBidInterstitialAd.java:165)

![image](https://github.com/pubnative/pubnative-hybid-android-sdk/assets/11819764/15dc304b-d3ec-4ce1-91f5-5f03d628e80a)

**Comment by eros902002** [comment]
@pendai closing this one, since the DB component has been replaced ever since.
