### ISSUE TITLE
PubNative Android 2.21.0 build error

### ISSUE THREAD

**Issue by Yurish-IL** [pubnative/pubnative-hybid-android-sdk#5]
Hi Guys, 
We upgrade PubNative version from `2.20.0` to the latest `2.21.0`.
For some reason, we are getting these errors:

`Caused by: org.gradle.internal.component.AmbiguousConfigurationSelectionException: The consumer was configured to find a runtime of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'mediation' with value 'regular', attribute 'compile' with value 'sources'. However we cannot choose between the following variants of com.google.guava:guava:32.1.3-android:`

Android Studio version: `Giraffe | 2022.3.1 Patch 2`
Gradle version : `6.7.0`
AGP version: `4.2.0`
Java version: `11`
minSdk :`21`
targetSdkVersion: `33`

Can you take a look?

**Comment by eros902002** [comment]
Hi @Yurish-IL . Thanks a lot for the report. We're looking into this right away and will get back to you with more info.

**Comment by eros902002** [comment]
Hi again @Yurish-IL . I've asked the team to take a look and we're most certain that the issue is regarding the gradle and Java versions. Currently we're using 7.5 and and Java 11. 
Is it a possibility for you to update your gradle version? Would like to understand your setup to see if there's any backwards compatibility we are missing.

**Comment by Yurish-IL** [comment]
Hi @eros902002, We are using Java 11 as well. What gradle version should we use?
I wasn't able to find any gradle version dependency in PubNative Android docs.

**Comment by eros902002** [comment]
> Hi @eros902002, We are using Java 11 as well. What gradle version should we use? I wasn't able to find any gradle version dependency in PubNative Android docs.

@Yurish-IL we're using 7.4.2 in the latest released version. I believe any Gradle 7 or 8 version will work

**Comment by Yurish-IL** [comment]
Thanks @eros902002 , updating gradle to 7.4.2 resolved this issue.
